# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lu_pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.CharField(default='Tuzick', max_length=16),
        ),
    ]
