# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lu_pet', '0002_auto_20180414_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('contacts', models.CharField(max_length=128)),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lu_pet.Advertisement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
